default:
  collection: earlytreaties
  solr_core: earlytreaties
  tei_solr_xsl: scripts/solr_transform_tei.xsl
development:
  solr_path: https://cdrhdev1.unl.edu/solr
production:
  solr_path: https://cors1601.unl.edu/solr
